/**
 * Stage 5: Emit generated TypeScript files.
 *
 * Primary format: Effect Schema declarations with inferred types.
 * Secondary format: Plain TypeScript interfaces (lightweight alternative).
 *
 * Generates one .ts file per module + a barrel index.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { FilteredModule, FilteredClass } from "./filter.js";
import type { TypeRegistry } from "./resolve.js";
import type { UhtFunction, UhtProperty } from "./parse.js";
import type { ResolvedConfig } from "../types.js";
import { engineClassToTs } from "../mappers/type-map.js";

// ── Public API ─────────────────────────────────────────────────────

export function emit(
  modules: readonly FilteredModule[],
  _registry: TypeRegistry,
  config: ResolvedConfig,
): void {
  mkdirSync(config.outDir, { recursive: true });

  for (const mod of modules) {
    const filePath = join(config.outDir, `${mod.name}.ts`);

    let content: string;
    switch (config.format) {
      case "effect-schema":
        content = emitEffectSchema(mod);
        break;
      case "types":
        content = emitTypes(mod);
        break;
      case "both":
        content = emitEffectSchema(mod);
        break;
    }

    writeFileSync(filePath, content, "utf-8");
  }

  // Barrel index
  const indexContent = modules
    .map((m) => `export * from "./${m.name}.js";`)
    .join("\n") + "\n";
  writeFileSync(join(config.outDir, "index.ts"), indexContent, "utf-8");

  console.log(`[codegen] Wrote ${modules.length} module(s) to ${config.outDir}`);
}

// ── Effect Schema emitter (primary) ────────────────────────────────

function emitEffectSchema(mod: FilteredModule): string {
  const lines: string[] = [
    `// Generated by @unreal-rc/codegen — do not edit`,
    `// Module: ${mod.name}`,
    ``,
    `import { Schema } from "effect";`,
    ``,
  ];

  for (const cls of mod.classes) {
    lines.push(...emitClassSchema(cls));
  }

  return lines.join("\n");
}

function emitClassSchema(cls: FilteredClass): string[] {
  const lines: string[] = [];
  const prefix = sanitizeIdentifier(cls.engineName);

  lines.push(`// ── ${prefix} ──`);
  lines.push(``);

  for (const fn of cls.functions) {
    const inputParams = getInputParams(fn);
    const returnParam = getReturnParam(fn);
    const schemaName = `${prefix}_${fn.SourceName}`;

    // Params schema
    if (inputParams.length === 0) {
      lines.push(`export const ${schemaName}Params = Schema.Struct({});`);
    } else {
      lines.push(`export const ${schemaName}Params = Schema.Struct({`);
      for (const param of inputParams) {
        lines.push(`  ${param.SourceName}: ${toSchemaExpr(param.EngineClassName)},`);
      }
      lines.push(`});`);
    }

    // Params inferred type
    lines.push(
      `export type ${schemaName}Params = typeof ${schemaName}Params.Type;`,
    );

    // Return schema (if non-void)
    if (returnParam) {
      lines.push(
        `export const ${schemaName}Return = ${toSchemaExpr(returnParam.EngineClassName)};`,
      );
      lines.push(
        `export type ${schemaName}Return = typeof ${schemaName}Return.Type;`,
      );
    }

    lines.push(``);
  }

  // Class-level function map — groups all functions for this class
  lines.push(`export const ${prefix} = {`);
  for (const fn of cls.functions) {
    const schemaName = `${prefix}_${fn.SourceName}`;
    const returnParam = getReturnParam(fn);
    lines.push(`  ${fn.SourceName}: {`);
    lines.push(`    functionName: "${fn.SourceName}" as const,`);
    lines.push(`    params: ${schemaName}Params,`);
    if (returnParam) {
      lines.push(`    returnSchema: ${schemaName}Return,`);
    }
    lines.push(`  },`);
  }
  lines.push(`} as const;`);
  lines.push(``);

  return lines;
}

// ── TypeScript types emitter (secondary) ───────────────────────────

function emitTypes(mod: FilteredModule): string {
  const lines: string[] = [
    `// Generated by @unreal-rc/codegen — do not edit`,
    `// Module: ${mod.name}`,
    ``,
  ];

  for (const cls of mod.classes) {
    lines.push(...emitClassTypes(cls));
    lines.push(``);
  }

  return lines.join("\n");
}

function emitClassTypes(cls: FilteredClass): string[] {
  const lines: string[] = [];
  const prefix = sanitizeIdentifier(cls.engineName);

  for (const fn of cls.functions) {
    const inputParams = getInputParams(fn);
    const returnParam = getReturnParam(fn);
    const typeName = `${prefix}_${fn.SourceName}`;

    // Params type
    if (inputParams.length === 0) {
      lines.push(`export type ${typeName}Params = Record<string, never>;`);
    } else {
      lines.push(`export interface ${typeName}Params {`);
      for (const param of inputParams) {
        lines.push(`  readonly ${param.SourceName}: ${engineClassToTs(param.EngineClassName)};`);
      }
      lines.push(`}`);
    }

    // Return type
    if (returnParam) {
      lines.push(
        `export type ${typeName}Return = ${engineClassToTs(returnParam.EngineClassName)};`,
      );
    }

    lines.push(``);
  }

  return lines;
}

// ── Schema expression mapping ──────────────────────────────────────

function toSchemaExpr(engineClassName: string): string {
  switch (engineClassName) {
    case "FloatProperty":
    case "DoubleProperty":
    case "IntProperty":
    case "UInt32Property":
    case "Int8Property":
    case "ByteProperty":
      return "Schema.Number";

    case "BoolProperty":
      return "Schema.Boolean";

    case "StrProperty":
    case "NameProperty":
    case "TextProperty":
      return "Schema.String";

    case "ObjectProperty":
    case "ClassProperty":
    case "SoftObjectProperty":
    case "SoftClassProperty":
    case "WeakObjectProperty":
      return "Schema.String";

    case "ArrayProperty":
      return "Schema.Array(Schema.Unknown)";
    case "MapProperty":
      return "Schema.Record({ key: Schema.String, value: Schema.Unknown })";
    case "SetProperty":
      return "Schema.Array(Schema.Unknown)";

    case "StructProperty":
    case "EnumProperty":
      // TODO: resolve to actual struct/enum schema via type registry
      return "Schema.Unknown";

    default:
      return "Schema.Unknown";
  }
}

// ── Helpers ────────────────────────────────────────────────────────

function getInputParams(fn: UhtFunction): readonly UhtProperty[] {
  return fn.Parameters.filter((p) => !p.PropertyFlags.includes("ReturnParm"));
}

function getReturnParam(fn: UhtFunction): UhtProperty | undefined {
  return fn.Parameters.find((p) => p.PropertyFlags.includes("ReturnParm"));
}

function sanitizeIdentifier(name: string): string {
  return name.replace(/^[UAFE](?=[A-Z_])/, "");
}
